In [1]:
!git clone https://github.com/anthropics/jacobian-lens.git

Cloning into 'jacobian-lens'...
remote: Enumerating objects: 67, done.
remote: Counting objects: 100% (2/2), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 67 (delta 0), reused 0 (delta 0), pack-reused 65 (from 2)
Receiving objects: 100% (67/67), 1.90 MiB | 31.39 MiB/s, done.
Resolving deltas: 100% (8/8), done.

In [2]:
cd jacobian-lens

/kaggle/working/jacobian-lens

In [3]:
%pip install -e .

Obtaining file:///kaggle/working/jacobian-lens
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from jlens==0.1.0) (2.10.0+cu128)
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (from jlens==0.1.0) (1.11.0)
Collecting transformers>=5.5 (from jlens==0.1.0)
  Downloading transformers-5.16.1-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from jlens==0.1.0) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=5.5->jlens==0.1.0) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers>=5.5->jlens==0.1.0) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers>=5.5->jlens==0.1.0) (2025.11.3)
Collecting tokenizers<0.24.0,>=0.23.1 (from transformers>=5.5->jlens==0.1.0)
  Downloading tokenizers-0.23.2-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.8 kB)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers>=5.5->jlens==0.1.0) (0.24.2)
Collecting safetensors>=0.8.0 (from transformers>=5.5->jlens==0.1.0)
  Downloading safetensors-0.8.0-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
Requirement already satisfied: tqdm>=4.60 in /usr/local/lib/python3.12/dist-packages (from transformers>=5.5->jlens==0.1.0) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->jlens==0.1.0) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->jlens==0.1.0) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->jlens==0.1.0) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->jlens==0.1.0) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->jlens==0.1.0) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch->jlens==0.1.0) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->jlens==0.1.0) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch->jlens==0.1.0) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->jlens==0.1.0) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch->jlens==0.1.0) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->jlens==0.1.0) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->jlens==0.1.0) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->jlens==0.1.0) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch->jlens==0.1.0) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch->jlens==0.1.0) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch->jlens==0.1.0) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch->jlens==0.1.0) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch->jlens==0.1.0) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->jlens==0.1.0) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch->jlens==0.1.0) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch->jlens==0.1.0) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch->jlens==0.1.0) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->jlens==0.1.0) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->jlens==0.1.0) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch->jlens==0.1.0) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch->jlens==0.1.0) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch->jlens==0.1.0) (1.5.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->jlens==0.1.0) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->jlens==0.1.0) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->jlens==0.1.0) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub->jlens==0.1.0) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub->jlens==0.1.0) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch->jlens==0.1.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->jlens==0.1.0) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=5.5->jlens==0.1.0) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=5.5->jlens==0.1.0) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=5.5->jlens==0.1.0) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=5.5->jlens==0.1.0) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers>=5.5->jlens==0.1.0) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers>=5.5->jlens==0.1.0) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers>=5.5->jlens==0.1.0) (0.1.2)
Downloading transformers-5.16.1-py3-none-any.whl (12.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 103.7 MB/s eta 0:00:0000:010:01
Downloading safetensors-0.8.0-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (516 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 516.0/516.0 kB 31.3 MB/s eta 0:00:00
Downloading tokenizers-0.23.2-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 91.6 MB/s eta 0:00:00:00:01
Building wheels for collected packages: jlens
  Building editable for jlens (pyproject.toml) ... done
  Created wheel for jlens: filename=jlens-0.1.0-0.editable-py3-none-any.whl size=8903 sha256=548239db5a0f833d80ab017d1bcd2ea9acae79b851e2dd4a5e4690c1dc2c0db0
  Stored in directory: /tmp/pip-ephem-wheel-cache-obyeay1b/wheels/1c/9b/32/c4a41a0ec872d1d1b4c77a876351e67d3de09dc57eee2c63c5
Successfully built jlens
Installing collected packages: safetensors, tokenizers, transformers, jlens
  Attempting uninstall: safetensors
    Found existing installation: safetensors 0.7.0
    Uninstalling safetensors-0.7.0:
      Successfully uninstalled safetensors-0.7.0
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.22.2
    Uninstalling tokenizers-0.22.2:
      Successfully uninstalled tokenizers-0.22.2
  Attempting uninstall: transformers
    Found existing installation: transformers 5.0.0
    Uninstalling transformers-5.0.0:
      Successfully uninstalled transformers-5.0.0
Successfully installed jlens-0.1.0 safetensors-0.8.0 tokenizers-0.23.2 transformers-5.16.1
Note: you may need to restart the kernel to use updated packages.

In [4]:
%pip install -U git+https://github.com/huggingface/transformers.git
%pip install -U "bitsandbytes>=0.46.1"

Collecting git+https://github.com/huggingface/transformers.git
  Cloning https://github.com/huggingface/transformers.git to /tmp/pip-req-build-cizxjdgi
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/transformers.git /tmp/pip-req-build-cizxjdgi
  Resolved https://github.com/huggingface/transformers.git to commit e4052f55b26e1e29ef7bd54b28600787bcc62ef8
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers==5.17.0.dev0) (1.11.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers==5.17.0.dev0) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==5.17.0.dev0) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==5.17.0.dev0) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers==5.17.0.dev0) (2025.11.3)
Requirement already satisfied: tokenizers<0.24.0,>=0.23.1 in /usr/local/lib/python3.12/dist-packages (from transformers==5.17.0.dev0) (0.23.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers==5.17.0.dev0) (0.24.2)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from transformers==5.17.0.dev0) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /usr/local/lib/python3.12/dist-packages (from transformers==5.17.0.dev0) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers==5.17.0.dev0) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers==5.17.0.dev0) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers==5.17.0.dev0) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers==5.17.0.dev0) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers==5.17.0.dev0) (4.15.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers==5.17.0.dev0) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers==5.17.0.dev0) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers==5.17.0.dev0) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers==5.17.0.dev0) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers==5.17.0.dev0) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers==5.17.0.dev0) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers==5.17.0.dev0) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers==5.17.0.dev0) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers==5.17.0.dev0) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers==5.17.0.dev0) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers==5.17.0.dev0) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers==5.17.0.dev0) (0.1.2)
Building wheels for collected packages: transformers
  Building wheel for transformers (pyproject.toml) ... done
  Created wheel for transformers: filename=transformers-5.17.0.dev0-py3-none-any.whl size=13451361 sha256=c28a7a848dfb12aa6732a1ecc6535399983f2158d058f9c820b51274d245685c
  Stored in directory: /tmp/pip-ephem-wheel-cache-5rwkt3zu/wheels/54/cb/3f/83103de5575c534436d6a4686686dead458238dfaf1147e98d
Successfully built transformers
Installing collected packages: transformers
  Attempting uninstall: transformers
    Found existing installation: transformers 5.16.1
    Uninstalling transformers-5.16.1:
      Successfully uninstalled transformers-5.16.1
Successfully installed transformers-5.17.0.dev0
Note: you may need to restart the kernel to use updated packages.
Collecting bitsandbytes>=0.46.1
  Downloading bitsandbytes-0.50.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: torch<3,>=2.4 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes>=0.46.1) (2.10.0+cu128)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes>=0.46.1) (2.0.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes>=0.46.1) (26.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (3.29.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch<3,>=2.4->bitsandbytes>=0.46.1) (1.5.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3,>=2.4->bitsandbytes>=0.46.1) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<3,>=2.4->bitsandbytes>=0.46.1) (3.0.3)
Downloading bitsandbytes-0.50.2-py3-none-manylinux_2_24_x86_64.whl (43.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.1/43.1 MB 44.6 MB/s eta 0:00:00:00:0100:01
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.50.2
Note: you may need to restart the kernel to use updated packages.

In [5]:
%pip install causal-conv1d
%pip install flash-linear-attention

Collecting causal-conv1d
  Downloading causal_conv1d-1.7.0.tar.gz (30 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from causal-conv1d) (2.10.0+cu128)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from causal-conv1d) (26.1)
Requirement already satisfied: ninja in /usr/local/lib/python3.12/dist-packages (from causal-conv1d) (1.13.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch->causal-conv1d) (3.29.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch->causal-conv1d) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch->causal-conv1d) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->causal-conv1d) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch->causal-conv1d) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->causal-conv1d) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch->causal-conv1d) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch->causal-conv1d) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->causal-conv1d) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->causal-conv1d) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->causal-conv1d) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch->causal-conv1d) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch->causal-conv1d) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch->causal-conv1d) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch->causal-conv1d) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch->causal-conv1d) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->causal-conv1d) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch->causal-conv1d) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch->causal-conv1d) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch->causal-conv1d) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->causal-conv1d) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->causal-conv1d) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch->causal-conv1d) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch->causal-conv1d) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch->causal-conv1d) (1.5.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch->causal-conv1d) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->causal-conv1d) (3.0.3)
Building wheels for collected packages: causal-conv1d
  error: subprocess-exited-with-error

  × Building wheel for causal-conv1d (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for causal-conv1d (pyproject.toml) ... error
  ERROR: Failed building wheel for causal-conv1d
Failed to build causal-conv1d
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (causal-conv1d)
Note: you may need to restart the kernel to use updated packages.
Collecting flash-linear-attention
  Downloading flash_linear_attention-0.5.2-py3-none-any.whl.metadata (45 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.6/45.6 kB 3.0 MB/s eta 0:00:00
Collecting fla-core==0.5.2 (from flash-linear-attention)
  Downloading fla_core-0.5.2-py3-none-any.whl.metadata (45 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.3/45.3 kB 2.7 MB/s eta 0:00:00
Requirement already satisfied: transformers>=4.45.0 in /usr/local/lib/python3.12/dist-packages (from flash-linear-attention) (5.17.0.dev0)
Requirement already satisfied: einops in /usr/local/lib/python3.12/dist-packages (from fla-core==0.5.2->flash-linear-attention) (0.8.2)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.45.0->flash-linear-attention) (1.11.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.45.0->flash-linear-attention) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.45.0->flash-linear-attention) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.45.0->flash-linear-attention) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.45.0->flash-linear-attention) (2025.11.3)
Requirement already satisfied: tokenizers<0.24.0,>=0.23.1 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.45.0->flash-linear-attention) (0.23.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers>=4.45.0->flash-linear-attention) (0.24.2)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.45.0->flash-linear-attention) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.45.0->flash-linear-attention) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers>=4.45.0->flash-linear-attention) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers>=4.45.0->flash-linear-attention) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers>=4.45.0->flash-linear-attention) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers>=4.45.0->flash-linear-attention) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers>=4.45.0->flash-linear-attention) (4.15.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.45.0->flash-linear-attention) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.45.0->flash-linear-attention) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.45.0->flash-linear-attention) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.45.0->flash-linear-attention) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=4.45.0->flash-linear-attention) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=4.45.0->flash-linear-attention) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=4.45.0->flash-linear-attention) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=4.45.0->flash-linear-attention) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=4.45.0->flash-linear-attention) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers>=4.45.0->flash-linear-attention) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers>=4.45.0->flash-linear-attention) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers>=4.45.0->flash-linear-attention) (0.1.2)
Downloading flash_linear_attention-0.5.2-py3-none-any.whl (399 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 399.6/399.6 kB 27.5 MB/s eta 0:00:00
Downloading fla_core-0.5.2-py3-none-any.whl (819 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 819.2/819.2 kB 41.9 MB/s eta 0:00:00
Installing collected packages: fla-core, flash-linear-attention
Successfully installed fla-core-0.5.2 flash-linear-attention-0.5.2
Note: you may need to restart the kernel to use updated packages.

In [6]:
import torch
import transformers
import jlens
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

model_id = "Qwen/Qwen3.6-27B" # Aligned with lens checkpoint version

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)

tok = AutoTokenizer.from_pretrained(model_id)
hf = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True
)

model = jlens.from_hf(hf, tok)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/12.8M [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 15 files:   0%|          | 0/15 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/851 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/202 [00:00<?, ?B/s]

In [7]:
lens = jlens.JacobianLens.from_pretrained(
    "neuronpedia/jacobian-lens", 
    filename="qwen3.6-27b/jlens/Salesforce-wikitext/Qwen3.6-27B_jacobian_lens_n1000.pt",
    revision="qwen-n1000"
)

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 1 files:   0%|          | 0/1 [00:00<?, ?it/s]

In [8]:
prompt = "Fact: The currency used in the country shaped like a boot is"

#No need to track gradient 
with torch.no_grad():
    # Use -1 to inspect the prediction following "is" (e.g. " Euro")
    lens_logits, model_logits, _ = lens.apply(model, prompt, positions=[-2])

for layer, logits in sorted(lens_logits.items()):
    tokens = [tok.decode([t]) for t in logits[0].topk(5).indices]
    print(f"Layer {layer:02d}: {tokens}")

[transformers] `causal_conv1d_fn` is falling back to its reference PyTorch implementation because `causal_conv1d` is not installed. This is correct but much slower; install `causal_conv1d` for the optimized kernel.

Layer 00: ['ting', 'ing', 'i', 'er', 'a']
Layer 01: ['er', 'ting', 'ing', ' –', 'i']
Layer 02: [' –', 'er', 'ting', 'ing', '**–']
Layer 03: [' --', " '--", ' <--', ' `_', 'ting']
Layer 04: ['er', 'ing', ' ***', 'ting', ' --']
Layer 05: ['er', 'ing', '的', ' ***', 'ting']
Layer 06: ['ting', ' `_', '的', ' `', 'ing']
Layer 07: ['ting', 'ing', 'er', ' `_', ' `']
Layer 08: ['ing', 'ting', 'er', 'tee', '`.`']
Layer 09: ['er', 'ing', '--', 'a', 'ting']
Layer 10: ['er', 'ing', 'a', 'i', 'ting']
Layer 11: ['er', 'ing', 'ting', ' _.', 'tee']
Layer 12: ['er', 'ing', 'ting', 'a', '--']
Layer 13: ['er', 'ing', 'a', 'ting', 'i']
Layer 14: ['er', 'a', '--', 'i', 'ing']
Layer 15: ['er', 'a', 'i', 'ing', '--']
Layer 16: ['er', 'a', 'i', 'ing', '--']
Layer 17: ['er', 'ing', 'a', 'i', 'ting']
Layer 18: ['er', ' --', ' boots', ' boot', 'ting']
Layer 19: ['er', ' --', 'ing', 'ting', ' boot']
Layer 20: [' --', 'er', 'a', ' `', 'i']
Layer 21: [' --', ' `', ' ``', '--', 'er']
Layer 22: [' --', ' ``', ' `', '--', ' _']
Layer 23: [' Italian', ' Italy', ' --', ' `', '意大利']
Layer 24: [' Italian', ' Italy', '意大利', 'Italy', ' Italians']
Layer 25: [' Italian', ' Italy', '意大利', 'Italy', ' Italians']
Layer 26: ['意大利', ' Italy', ' Italian', 'Italy', ' Italians']
Layer 27: [' Italy', ' Italian', '意大利', 'Italy', ' Italians']
Layer 28: ['意大利', ' Italy', 'Italy', ' Italian', ' __']
Layer 29: [' __', '意大利', ' ____', ' Italy', ' ___']
Layer 30: ['意大利', ' __', ' Italy', 'Italy', ' ____']
Layer 31: ['意大利', '____', ' ____', ' __', ' ______']
Layer 32: ['____', ' ____', '意大利', ' ______', ' ___']
Layer 33: ['意大利', '____', ' ____', 'Italy', ' ______']
Layer 34: ['意大利', 'Italy', ' Italy', '____', ' ____']
Layer 35: ['意大利', ' Italy', 'Italy', ' Italian', '____']
Layer 36: ['意大利', ' Italy', 'Italy', ' Italian', 'Italian']
Layer 37: ['意大利', ' Italy', 'Italy', ' Italian', 'Italian']
Layer 38: ['意大利', ' Italy', 'Italy', ' Italian', 'Italian']
Layer 39: ['意大利', ' Italy', 'Italy', ' Italian', 'Italian']
Layer 40: [' Italy', 'Italy', '意大利', ' Italian', 'Italian']
Layer 41: [' Italy', '意大利', 'Italy', ' Italian', 'Italian']
Layer 42: [' Italy', 'Italy', '意大利', ' Italian', 'Italian']
Layer 43: [' Italy', '意大利', 'Italy', ' Italian', 'Italian']
Layer 44: [' Italy', 'Italy', '意大利', ' Italian', '____']
Layer 45: [' Italy', 'Italy', '意大利', ' Italian', 'Italian']
Layer 46: [' Italy', 'Italy', '意大利', ' Italian', 'Italian']
Layer 47: [' Italy', 'Italy', ' Italian', '意大利', 'Italian']
Layer 48: [' Italy', 'Italy', ' Italian', '意大利', 'Italian']
Layer 49: [' Italy', ' Italian', 'Italy', '____', '意大利']
Layer 50: [' Italy', ' is', ' was', ' Italian', 'Italy']
Layer 51: [' Italy', ' is', ' was', ' Italian', 'Italy']
Layer 52: [' is', ' Italy', ' was', ' Italian', 'Italy']
Layer 53: [' Italy', ' is', ' Italian', ' was', '意大利']
Layer 54: [' is', ' Italy', '-shaped', ' was', ' shaped']
Layer 55: [' is', ' Italy', '-shaped', ' shaped', ' was']
Layer 56: [' is', ' Italy', '-shaped', 'Italy', ' shaped']
Layer 57: [' is', ' Italy', ' shaped', '-shaped', ' shape']
Layer 58: [' boot', ' Boot', 'boot', ' shaped', 'Boot']
Layer 59: [' Italy', ' is', ' boot', ' Italian', ' shaped']
Layer 60: [' is', ' Italy', ' boot', ' Italian', 'Italy']
Layer 61: [' is', ' Italy', ' boot', 'boot', ' shaped']
Layer 62: [' is', ',', '.', ' boot', ' shaped']

In [9]:
import gzip
import json

from jlens.examples import EXAMPLES, resolve_prompt
from jlens.vis import build_page, compute_slice, notebook_iframe

# English gloss for Qwen's Chinese/Japanese/Korean vocab tokens (machine-
# generated, best-effort), shown next to
# the token in the page (alt_token=).
gloss = {
    int(k): v for k, v in json.load(gzip.open("assets/qwen_gloss.json.gz")).items()
}

example = next(e for e in EXAMPLES if e.slug == "multihop")
prompt = resolve_prompt(example, tok)

slice_data = compute_slice(
    model,
    lens,
    prompt,
    layer_stride=2,
    # Empirically on Qwen, the interesting word tokens trail punctuation and
    # single-character tokens in the raw top-K; mask to word-like tokens only.
    mask_display=True,
)
page, _, _ = build_page(
    slice_data,
    prompt,
    title=example.section,
    description=example.description,
    alt_token=gloss,
)
notebook_iframe(page)

In [10]:
import json
from collections import Counter

with open("data/experiments/probe-swap.json") as file:
    raw = json.load(file)

probe_swap_data = raw["items"]

prompts = [entry["prompt"] for entry in probe_swap_data]

tokenizer = model.tokenizer

layer_counts: dict[int, Counter] = {}
position_layer_counts: dict[tuple[int, int], Counter] = {}

for prompt in prompts:
    input_ids = model.encode(prompt)
    seq_len = input_ids.shape[1]

    lens_logits, model_logits, _ = lens.apply(model, prompt, positions=list(range(seq_len)))

    for layer, logits in lens_logits.items():
        top1_per_position = logits.argmax(dim=-1).tolist()
        layer_counts.setdefault(layer, Counter()).update(top1_per_position)
        for position, token_id in enumerate(top1_per_position):
            position_layer_counts.setdefault((position, layer), Counter())[token_id] += 1

In [13]:
import pandas as pd
def decode(token_id: int) -> str:
    return tokenizer.decode([token_id], clean_up_tokenization_spaces=False)


df_by_layer = (
    pd.DataFrame(
        {
            "layer": layer,
            "top_token": decode(counter.most_common(1)[0][0]),
            "count": counter.most_common(1)[0][1],
            "total_seen": sum(counter.values()),
        }
        for layer, counter in sorted(layer_counts.items())
    )
    .set_index("layer")
)


df_grid_long = pd.DataFrame(
    {"position": position, "layer": layer, "top_token": decode(counter.most_common(1)[0][0])}
    for (position, layer), counter in position_layer_counts.items()
)
df_by_position = df_grid_long.pivot(index="position", columns="layer", values="top_token").sort_index()

In [14]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

In [15]:
df_by_position

layer,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62
position,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,a,ually,a,＿＿,ually,ually,**「,**「,**「,ually,a,``,``,ually,``,``,a,a,``,\',<|endoftext|>,**「,``,``,.__,**「,**「,**「,**「,**「,**「,**「,``,**‘,**「,**,**,``,**,**,**,**,?\,?\,?**,?**,**,**,**,**,…**,!**,!**,!**,oring,oring,oring,oring,-check,oring,oring,oring,oring
1,.,VERY,.,专栏收录该内容,pornstar,​​,**«,pornstar,"\""",?\,...\,______,truths,truths,!,kids,kids,真相,真相,真相,Facts,真相,Facts,__,__,...\,facts,__,...\,____,____,**【,**【,**【,science,Facts,science,science,Fact,Scientists,Scientists,facts,humans,Earth,Earth,humans,humans,humans,humans,humans,humans,humans,humans,humans,electricity,electricity,electricity,pollution,electricity,Some,fire,Some,Some
2,–,–,–,Shemale,专栏收录该内容,专栏收录该内容,**「,Shemale,**「,"\""\","\""","\""","\""",｢,"\""","\""","\""","\""","\""","\""","\""","\""","\""",\n\n,\n\n,\n\n,\n\n,\n\n,\n\n,____,____,____,______,______,______,______,______,animals,animals,animals,animals,animals,animals,animals,animals,animals,animals,animals,animals,animals,American,American,temperature,temperature,temperature,temperature,temperature,temperature,temperature,temperature,temperature,temperature,temperature
3,.,–,–,**○,**-,**:,**,**,**«,",",",",isation,isation,isation,of,isation,of,-capital,-capital,-capital,-capital,-capital,of,of,of,cities,cities,city,cities,cities,cities,cities,city,______,city,city,cities,cities,city,cities,city,cities,cities,cities,cities,cities,cities,cities,cities,cities,city,of,of,city,city,city,city,city,city,city,of,of,of
4,.,–,–,milfs,.,​​,**„,**„,​​,",",.,",",city,",",",",",",",",",",​​,​​,,city,city,city,city,city,city,______,__,______,______,______,______,______,______,______,______,Canada,Canada,Canada,Canada,Canada,country,______,Canada,Canada,Canada,Canada,Canada,Australia,Canada,France,France,France,France,France,of,of,of,of,of,of,of
5,.,–,.,milfs,加拿大的,​​,**「,**„,.,",",.,.,.,",",.,of,",",",",King,",",",","\""",King,many,British,British,British,__,______,______,______,______,______,______,______,______,______,______,Kingdom,Kingdom,Kingdom,Kingdom,Kingdom,Kingdom,Kingdom,Republic,Kingdom,Kingdom,Republic,Republic,Republic,Kingdom,Republic,Republic,Republic,Republic,Republic,Republic,United,United,United,United,United
6,.,–,.,milfs,.,.,.,.,.,",",.,.,.,of,.,of,",",",",countries,countries,which,countries,countries,countries,countries,countries,countries,countries,______,______,______,______,______,______,______,______,______,______,countries,countries,countries,countries,countries,countries,countries,countries,countries,countries,countries,countries,countries,Country,where,where,where,where,where,where,where,where,where,is,is
7,.,–,–,milfs,\n,.,.,\n,.,",",.,\n,\n,​​,--,​​,最新发布,最新发布,​​,​​,\n,​​,\n,'',\n,countries,countries,countries,\n,______,\n,______,____,____,____,____,____,____,Country,____,Country,Country,____,____,Country,Country,Country,Country,Country,Mount,Mount,Mount,Mount,Mount,Mount,Mount,Mount,Mount,Mount,Mount,Mount,Mount,Mount
8,.,–,.,milfs,.,.,.,.,.,",",",",",",",",",",",",​​,",",",",​​,​​,\n,​​,``,",",\n,\n,countries,______,______,______,______,______,______,______,______,______,______,______,Country,is,Country,liquids,liquids,______,is,is,Country,Country,is,Country,Country,National,National,George,varies,depends,determines,Mount,Mount,Mount,Mount,is,is
9,.,–,.,milfs,​​,​​,\n,\n,.,",",.,´t,´t,´t,.,​​,s,´t,´t,atleast,\n\n,``,``,``,whilst,___,___,___,______,______,______,______,______,______,______,______,______,______,______,？,cities,chemical,cities,______,chemical,cities,____,____,Chemical,located,located,located,located,located,located,located,located,located,located,located,located,located,located
10,.,–,.,milfs,.,.,.,.,.,",",.,.,.,",",.,​​,",",",",anyways,",",",",().,amongst,``,",",___,___,______,______,______,______,______,______,______,______,______,______,______,______,water,liquids,metals,metals,metals,metals,metals,____,water,water,humans,is,is,is,is,is,is,is,is,element,is,is,is,is
11,.,–,.,milfs,.,.,.,.,.,",",.,.,.,.,.,also,",",",",s,",",\n\n,arily,``,``,oxide,___,___,___,___,___,______,______,____,______,______,______,______,______,______,____,chemistry,chemical,chemical,____,____,chemical,____,____,Chemical,Chemical,is,is,is,is,is,is,is,is,chlorine,is,is,is,is
12,.,–,.,milfs,s,.,.,.,.,",",.,",",ness,",",",",",",",",",",milfs,hium,\n\n,``,__,",",",",__,___,___,__,__,___,___,___,___,____,______,___,_____,atomic,name,name,atomic,atomic,_____,name,name,name,name,...\,...\,is,is,is,is,is,is,is,atomic,is,is,is,is,is
13,.,–,.,milfs,_____,.,s,.,.,",",.,.,ity,",",.,ity,",",ity,ity,\n\n,\n\n,``,__,__,\n\n,___,___,___,___,___,___,___,___,___,______,______,______,______,______,atomic,atomic,atomic,atomic,____,____,____,____,____,____,____,____,____,is,is,is,is,is,is,number,is,is,is,is
14,.,–,.,milfs,.,.,.,.,.,",",.,",",",",",",",",",",",",",",of,of,\n\n,of,number,--,\n\n,___,___,___,___,______,______,______,____,______,______,______,______,______,______,______,number,____,____,____,____,____,____,____,____,____,____,____,____,____,Atomic,atomic,Atomic,atomic,atomic,atomic,eighty,eighty,
15,.,–,.,milfs,erez,​​,”,​​,.,",",.,"\""","\""",´s,.,"\""",",",´s,'','',\n\n,'','','','',___,___,___,____,____,___,___,___,______,______,____,______,______,______,____,？,____,____,____,____,____,____,____,?\,____,____,____,____,atomic,is,is,元素,atomic,atomic,is,is,is,8
16,.,–,​​,Shemale,s,​​,.,.»,.,",",.,s,s,.,.,",",",",s,ified,s,\n\n,``,",",--,\n\n,___,___,___,___,___,___,___,____,____,？,？,？,？,？,？,oxygen,oxygen,oxygen,oxygen,____,____,____,____,____,____,____,____,is,is,is,is,is,is,Oxygen,oxygen,is,is,2
17,.,–,.,专栏收录该内容,.,.,s,.,.,",",.,s,s,.,.,in,",",s,s,",",\n\n,``,__,--,\n\n,",",___,__,__,___,___,___,______,______,______,______,______,______,______,？,？,______,______,____,______,____,____,____,____,____,called,called,is,is,is,is,called,called,called,called,is,is,is
18,.,–,.,专栏收录该内容,.,.,.,.,.,",",.,nevertheless,nevertheless,",",presently,nevertheless,",",nonetheless,nonetheless,'',\n\n,'',--,--,__,___,___,___,__,______,____,___,___,______,______,______,______,______,______,______,______,______,______,____,____,____,____,____,____,____,____,____,____,is,is,is,固态,固态,固态,solid,solid,solid,solid
19,.,–,–,milfs,s,s,s,s,.,",",.,s,s,s,s,s,s,s,s,--,\n\n,--,--,--,\n\n,___,___,___,____,____,____,____,____,____,______,______,____,？,______,____,____,turtles,orchestra,____,____,___,____,____,___,___,turtles,orchestra,____,orchestra,orchestra,orchestra,orchestra,壳,shell,shell,shell,shell,the
20,.,–,–,milfs,s,.,\n,s,.,–,.,\r\n,\_,.,.,’,‘,"\""","\""",’,\n\n,'',``,--,\n\n,\n\n,.,.,___,___,___,___,____,______,______,______,______,____,______,______,body,body,____,____,____,____,____,____,____,__.,was,called,____,____,protects,protects,protects,protects,protects,protects,protects,is,is
21,.,–,–,``,**:**,.,**「,**「,.,",",.,**「,**「,_,_,_,really,____,\n\n,--,\n\n,___,'','',\n\n,___,___,___,______,______,____,______,____,______,______,______,______,______,______,______,______,______,______,______,______,___,___,___,called,____,called,called,was,was,is,is,is,is,called,is,is,is,is
22,.,–,–,Shemale,**:**,港币,!!!,**「,''',''',''',''','','','',--,'','',--,--,--,--,--,--,\n\n,___,___,___,___,___,___,___,____,___,____,______,______,______,______,______,________,____,______,____,____,____,___,____,____,.\,叫做,叫做,is,is,is,is,is,shell,shell,shell,shell,shell,a
23,.,–,–,sprozess,sprozess,.,s,sburg,_.,s,s,<|fim_suffix|>,s,s,s,s,s,s,s,s,\n\n,<|fim_suffix|>,``,--,\n\n,____,___,\n\n,\n\n,___,____,____,___,____,____,____,____,____,____,turtles,armor,armor,armor,armor,____,____,____,____,____,__,__.,"\""",armor,armor,shell,shell,shell,shell,shell,shell,shell,shell,shell
24,.,–,.,Shemale,률은,港币,\n,avour,avour,-Cds,**|,**○,**「,milfs,anyways,anyways,anyways,什么,**【,____,\n\n,____,\r\n\r\n,\r\n\r\n,\n\n,\n\n,___,____,____,____,____,____,___,____,____,______,______,nighttime,nighttime,nighttime,nighttime,nighttime,nighttime,nighttime,nighttime,nighttime,nighttime,____,____,____,____,____,____,____,nighttime,nighttime,nighttime,nighttime,nighttime,nighttime,nighttime,night,night
25,–,aleigh,–,milfs,**:,maths,´t,**:,´s,avourite,´,organiser,´,´s,whilst,whilst,whilst,whilst,'',s,\n\n,kì,\n\n,--,\n\n,\n\n,\n\n,\n\n,\n\n,,,\n\n,\n\n,\n\n,？,？,？,week,week,week,week,week,week,week,____,week,____,____,____,____,___,Tuesday,Tuesday,Tuesday,Tuesday,Friday,Wednesday,Friday,Friday,Wednesday,Wednesday,Wednesday,3

In [16]:
df_by_layer

          top_token  count  total_seen
layer
0                 .    862        1496
1                 –    525        1496
2                 .    402        1496
3             milfs    299        1496
4                 .    169        1496
5                 .    253        1496
6               **「    243        1496
7                 .    155        1496
8                 .    357        1496
9                 ,    480        1496
10                .    362        1496
11               ``    116        1496
12               ``    127        1496
13                ,    180        1496
14                .    151        1496
15               ``    124        1496
16                ,    234        1496
17                ,    153        1496
18               \"    133        1496
19               \"    136        1496
20             \n\n    131        1496
21               \"    139        1496
22               ``    190        1496
23               ``    183        1496
24             \n\n    167        1496
25              ___    123        1496
26              ___    159        1496
27               __    188        1496
28           ______    190        1496
29           ______    260        1496
30             ____    292        1496
31           ______    268        1496
32           ______    337        1496
33           ______    366        1496
34           ______    350        1496
35           ______    412        1496
36           ______    359        1496
37           ______    176        1496
38           ______    149        1496
39          animals    125        1496
40          animals    138        1496
41          animals    135        1496
42          animals    134        1496
43          animals    136        1496
44          animals    135        1496
45          animals    132        1496
46          animals    128        1496
47             ____    134        1496
48          animals    129        1496
49          animals    119        1496
50           humans    117        1496
51           humans    107        1496
52           humans    107        1496
53           humans    108        1496
54               is    100        1496
55               is     95        1496
56      temperature     94        1496
57      temperature     93        1496
58      temperature     93        1496
59      temperature     93        1496
60      temperature     93        1496
61               is    130        1496
62               is    130        1496

# **Experimenting with vector swapping:**

In [ ]:
#Preliminary algorithm for swapping J space vectors with adjustable strength based on the J-space paper.

W_U = hf.get_output_embeddings().weight #Get unembedding vector

def get_lens_vectors(layer, source_id, target_id):
    '''Get relevant J space vectors. The J lens vector is pre transposed at storage.'''
    J_l = lens.J[layer]
    v_s = W_U[source_id] @ J_l 
    v_t = W_U[target_id] @ J_l
    return v_s, v_t
    
def make_swap_hook(v_s, v_t, positions=None, alpha=1.0):
    '''The idea is like the one of the paper, the goal is to break up the hidden state h into the c1 * source vector + c2 * target vector + w
        where w is orthogonal. This is so we can perform magnitude aware swapping where we simply swap the proportions of each vector in h 
        to both source and target vectors a method of doing so involves le
    
    '''    
    V = torch.stack([v_s, v_t], dim=1)
    V_pinv = torch.linalg.pinv(V) #Get pseudo inverse of the source and target vectors,the idea is treating h like a linear regression problem and solving via least squares using pseeudo inverese
    def hook(module, input, output):
        h = output[0] if isinstance(output, tuple) else output # Shape (1,seq,d_model) batch == 1 for inference.
        pos = positions if positions is not None else slice(None)
        h_sel = h[:, pos, :] 
        c = h_sel @ V_pinv.T   #Getting coeffecients, how much of v_s is in selected h, how much of v_t is in selcted h Shape (batch(1), n_pos, 2)
        c_swapped = c.flip(dims=[-1]) * alpha + c * (1 - alpha)  # swap w/ optional strength
        delta = (c_swapped - c) @ V.T       # Actual scaled vectors to be added/subtracted after calculating c values

        h[:, pos, :] = h_sel + delta #

        if isinstance(output, tuple):
            return (h,) + output[1:]
        return h
        
    return hook